spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attendance_db?useSSL=false&serverTimezone=UTC
    username: spring
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true