apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: approval-service
  template:
    metadata:
      labels:
        app: approval-service
    spec:
      containers:
        - name: approval-service
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
