# gateway-rbac.yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-service-account
  namespace: default # gateway가 배포된 namespace로 수정하세요.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gateway-service-role
  namespace: default # gateway가 배포된 namespace로 수정하세요.
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services", "pods", "endpoints"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-service-rolebinding
  namespace: default # gateway가 배포된 namespace로 수정하세요.
subjects:
  - kind: ServiceAccount
    name: gateway-service-account
roleRef:
  kind: Role
  name: gateway-service-role
  apiGroup: rbac.authorization.k8s.io